# Project Information
# https://www.mkdocs.org/user-guide/configuration/#project-information
site_name: Schema Kenerator
site_url: https://smiley4.github.io/schema-kenerator/
site_description: Analyze kotlin types, extract information and generate schemas .

# Repository
repo_name: schema-kenerator
repo_url: https://github.com/SMILEY4/schema-kenerator


# Documentation Layout
# https://www.mkdocs.org/user-guide/configuration/#documentation-layout
nav:
  - Project: index.md
  - User Guide:
    - Concept: user_guide/concept.md
    - Modules: user_guide/modules.md
    - Analyzing Types:
      - Reflection: user_guide/analyzing_types_reflection.md
      - Kotlinx.Serialization: user_guide/analyzing_types_kotlinx_serialization.md
    - Generating Schemas:
      - JSON Schema: user_guide/generating_json_schema.md
      - Swagger Schema: user_guide/generating_swagger_schema.md
    - Customization: user_guide/customization.md
  - Changelog: changelog.md


# Validation
# # https://www.mkdocs.org/user-guide/configuration/#validation
validation:
  nav:
    omitted_files: warn
    not_found: warn
    absolute_links: warn
  links:
    not_found: warn
    absolute_links: warn
    unrecognized_links: warn


# Configuration
# https://www.mkdocs.org/user-guide/configuration/#build-directories
theme:
  name: material
  icon:
    logo: material/library
    repo: fontawesome/brands/github
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  features:
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.expand
    - navigation.indexes
    - navigation.footer
    - toc.integrate
    - search.suggest
    - search.share
    - content.code.copy
    - content.code.annotate
extra_css:
  - assets/stylesheets/extra.css
extra:
  version:
      provider: mike
plugins:
  - search
  - privacy


# Formatting Options
# https://www.mkdocs.org/user-guide/configuration/#formatting-options
markdown_extensions:
  # https://python-markdown.github.io/extensions/
  - attr_list
  - admonition
  - md_in_html
  - tables
  # https://facelessuser.github.io/pymdown-extensions/extensions/arithmatex/
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.details
#  - pymdownx.snippets:
#      base_path: [ 'examples/src/main/kotlin/io/github/smiley4/ktoropenapi/examples' ]
#      dedent_subsections: True
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      options:
        custom_icons:
          - './docs/assets/icons'